### PR TITLE
Define the WebVTT rules for extracting the chapter title

### PR DESCRIPTION
**Pull request by foolip**
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27102

This doesn't actually define the WebVTT rules, that is for later.

### CODE REVIEW

**Comment by foolip** [comment]
I also throw a move commit in there. Use `git show -w --word-diff` to confirm that there's nothing else in there.

**Comment by foolip** [comment]
OK, I went the whole way in the PR, renamed to reflect that.

**Comment by foolip** [comment]
Ping

**Comment by silviapfeiffer** [comment]
Sorry about the delay - this needs a look from the command-line and haven't had time yet. Doing it now...

**Comment by silviapfeiffer** [comment]
Nice!

**Comment by foolip** [comment]
Thanks for the review!

**Comment by silviapfeiffer** [comment]
Any time! (well... when I have the headspace :-)

**Pull request merged**
