### PR TITLE
Setup gh actions

### PR DESCRIPTION
**Pull request by himorin**
I've checked
- output from HEAD of PR 492 and `index.html` in gh-pages is the same, except for syntax used by bikeshed
- configured to use main branch as a source, and gh-pages as a destination

and propose:
- remove index.html in gh-pages (done in this PR), to prevent local and/or remote crash

If fine, please (or I can take actions):
- switch source of github page to gh-pages (from main)
- merge this PR first
- merge PR #492 second, and check all working

### CODE REVIEW

**Comment by gkatsev** [comment]
Should we include `index.html` in .gitignore so that it won't get checked in by people into the repo? We'd want to exclude .gitignore from the deploy copy as well.

Otherwise, this LGTM. Thanks @himorin!

**Comment by himorin** [comment]
> Should we include `index.html` in .gitignore so that it won't get checked in by people into the repo? We'd want to exclude .gitignore from the deploy copy as well.

updated.
(`/html5/` in `.gitignore` should be removed??)

**Review by gkatsev — APPROVED** [review]

**Comment by himorin** [comment]
Let me propose as follows:

- merge this #494 first (should work incl. GHActions)
- change github pages source to gh-pages branch
- cleaning up files in gh-pages branch, since we now have the same for main and gh-pages 
- merge other PRs

**Comment by gkatsev** [comment]
@himorin that sounds great to me!

**Comment by gkatsev** [comment]
@himorin looks like the action failed :( https://github.com/w3c/webvtt/runs/1984601204#step:5:80

**Comment by gkatsev** [comment]
Actually, looks like it succeeded but then the rest of the action had an issue? https://github.com/w3c/webvtt/commit/34e1ab9081073d9ad5479541cda228e6ecc0c4f4

**Comment by himorin** [comment]
Ah! I forgot recent update... (which I did for other WG) 
let me open another PR.

**Pull request merged**
