### PR TITLE
Use the W3C SOFTWARE AND DOCUMENT NOTICE AND LICENSE

### PR DESCRIPTION
**Pull request by silviapfeiffer**
This brings the spec in line with the LICENSE.md file of the WebVTT repo
https://github.com/w3c/webvtt/blob/gh-pages/LICENSE.md

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
@palemieux I'm confused - what are you suggesting? Can you make a new pull request for it?

**Comment by palemieux** [comment]
Ok. Will create separate PR.

**Comment by palemieux** [comment]
@silviapfeiffer This PR suggests that "Contributions to Specifications are made under the W3C COMMUNITY CONTRIBUTOR LICENSE AGREEMENT (CLA)". I think contributions to WebVTT going forward should be made under the [TTWG CLA](https://github.com/w3c/imsc/blob/master/CONTRIBUTING.md) since the contributions are intended to be integrated in a Rec Track document, which are governed by the W3C Patent Policy and Document License. The TTWG CLA require a patent licensing commitment upfront from contributots... so no need to chase contributors after the fact. Hope this makes sense. Let me know if you need additional information.

**Comment by palemieux** [comment]
@silviapfeiffer See proposal at https://github.com/w3c/webvtt/pull/438

**Comment by silviapfeiffer** [comment]
OK so #438 is suggesting a change on the repository which includes use of the license that this PR is suggesting to update the spec to.
Can we please land this PR so the spec conforms to the more modern W3C document license?

**Comment by palemieux** [comment]
@silviapfeiffer Happy to limit this PR to fixing the specification, and defer #438 to a different issue. Seemed more logical to fix all license issues together.

**Comment by silviapfeiffer** [comment]
Not yet. Will do before landing. 😀

**Comment by silviapfeiffer** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by silviapfeiffer** [comment]
I had to mark it as non-substantive to merge, because I'm currently in the process of transferring to Invited Expert status, sigh.

**Pull request merged**
