### PR TITLE
Editorial: Align with Web IDL specification

### PR DESCRIPTION
**Pull request by autokagami**
This is an automated pull request to align the spec with the latest Web IDL specification.

Currently the autofix might introduce some awkward code formatting, so please feel free to modify the formatting.

Please file an issue on https://github.com/saschanaz/webidl-updater/issues/new if you think this PR is invalid or should be enhanced.

The following is the validation messages from webidl2.js, which may help understanding this PR:

```
Validation error at line 8 in webvtt1,0, inside `interface VTTCue`:
 Constructor(double startTime,
 ^ Constructors should now be represented as a `constructor()` operation on the interface instead of `[Constructor]` extended attribute. Refer to the [WebIDL spec section on constructor operations](https://heycam.github.io/webidl/#idl-constructors) for more information.

Validation error at line 3 in webvtt1,1, inside `interface VTTRegion`:
 Constructor]
 ^ Constructors should now be represented as a `constructor()` operation on the interface instead of `[Constructor]` extended attribute. Refer to the [WebIDL spec section on constructor operations](https://heycam.github.io/webidl/#idl-constructors) for more information.
```

***

### :boom: Error: 400 Bad Request :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 26, 2021, 6:10 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebvtt%2Ff5c28140f619a6f7cd301345515785ced4076d41%2Findex.bs&md-warning=not%20ready)

```
Error running preprocessor, returned code: 2.
WARNING: The following &lt;var>s were only used once in the document:
  'stylesheets', in algorithm 'WebVTT parser algorithm'
  'input', in algorithm 'WebVTT region settings parsing'
  'input', in algorithm 'WebVTT region objects'
  'regions', in algorithm 'collect WebVTT cue timings and settings'
  'input', in algorithm 'parse the WebVTT cue settings'
  'regions', in algorithm 'parse the WebVTT cue settings'
  'language', in algorithm 'WebVTT cue text parsing rules'
  'cue', in algorithm 'WebVTT rules for extracting the chapter
title'
  'cue', in algorithm 'WebVTT rules for extracting the chapter title'
  'language', in algorithm 'Processing model'
  'language', in algorithm 'rules for updating the display of WebVTT text tracks'
  'nodes', in algorithm 'Processing cue settings'
  'left', in algorithm 'apply WebVTT cue settings'
  'top', in algorithm 'apply WebVTT cue settings'
  'max dimension', in algorithm 'apply WebVTT cue settings'
  'video', in algorithm 'Obtaining CSS boxes'
  'startTime', in algorithm 'VTTCue construction'
  'endTime', in algorithm 'VTTCue construction'
  'text', in algorithm 'VTTCue construction'
If these are not typos, please add an ignore='' attribute to the &lt;var>.
FATAL ERROR: The [Constructor] extended attribute (on VTTCue) is deprecated, please switch to a constructor() method.
 ✘  Did not generate, due to fatal errors
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/webvtt%23492.)._
</details>

### CODE REVIEW

**Comment by foolip** [comment]
@gkatsev would you be able to review/merge this?

**Review by gkatsev — APPROVED** [review]

**Comment by gkatsev** [comment]
@foolip yes, sorry, I kept forgetting about this when getting distracted by other things.

**Comment by gkatsev** [comment]
Let me circle back @himorin about #494 and then I'll merge the PRs

**Comment by himorin** [comment]
> Let me circle back @himorin about #494 and then I'll merge the PRs

I think we can go to merge #494 with some following works (update github pages target, cleaning up files in gh-pages repo). (will comment in #494 in details)

**Pull request merged**
