### PR TITLE
Make "best position" never overlap any other cue

### PR DESCRIPTION
**Pull request by kleopatra999**
https://www.w3.org/Bugs/Public/show_bug.cgi?id=17483#c3

### CODE REVIEW

**Comment by foolip** [comment]
What's going on here? I did not mean to merge this to the spec yet, this branch is for discussion in https://codereview.chromium.org/880873002/

**Comment by silviapfeiffer** [comment]
? Should this be rejected?

**Comment by foolip** [comment]
Yes it should, I was just hoping for some explanation. Closing.

**Comment by silviapfeiffer** [comment]
Yeah, I am surprised about this, too. Probably some accident.

**Pull request closed without merging**
