### PR TITLE
Prepare a new WD.

### PR DESCRIPTION
**Pull request by silviapfeiffer**
I prepared a new WD for the WebVTT spec from the current CG editor's draft.
See the archives directory.
I cannot land it any more in the W3C CVS repository, sorry.

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
Simon, when you return, the Overview file has in the meantime been published as the new WD. Would be good to land this branch. All the changes to the bikeshed file have been made so the normal editor's draft continues to be created as before.

**Comment by nigelmegitt** [comment]
@silviapfeiffer maybe a typo in that commit summary, but it's the Timed Text Working Group not the TTML WG.

**Comment by silviapfeiffer** [comment]
@nigelmegitt apologies - I wasn't thinking too much about it when I wrote it, sorry :-)

**Comment by zcorpan** [comment]
Landed. Thank you!!

**Comment by silviapfeiffer** [comment]
It was exhausing, but fun. :-) Thanks for merging.

**Pull request merged**
