### PR TITLE
Updates to region identifier, CSS selection & existance.

### LINKED ISSUE #314: CR bug: region identifiers
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28474

We don't understand how we can remove region IDs completely as they are used to associate regions with cues.

It seems we could indeed have a ::region(id) selector.

If we create a ::region(id) selector, we will also need to apply the id to the DocumentFragment and therefore resolve https://www.w3.org/Bugs/Public/show_bug.cgi?id=28471 .

### PR DESCRIPTION
**Pull request by silviapfeiffer**
* Make sure regions only get created when they have an identifier
* introduce a ::cue-region(selector) pseudo-element

Addresses https://www.w3.org/Bugs/Public/show_bug.cgi?id=28471 and https://www.w3.org/Bugs/Public/show_bug.cgi?id=28474

Closes #314

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by dwsinger** [comment]
LGTM

**Comment by plehegar** [comment]
Landed following @silviapfeiffer recommendation.

**Comment by silviapfeiffer** [comment]
Thanks, we'll get Simon's review when he's back. Onto preparing a new WD!

**Comment by nigelmegitt** [comment]
Guys, I see in https://github.com/w3c/webvtt/pull/349#issuecomment-310885718 that this was marked as non-substantive for IPR, but in my reading it is definitely substantive. I think telling ash-nazg that the change is non-substantive is not the right approach in these cases. Rather there should be an alternative option to say "it is substantive and as the author I'm granting IPR as required for a W3C Rec track document".

@silviapfeiffer @dwsinger @plehegar perhaps you already agreed the IPR issues offline? I can't see it in the issue.

**Comment by dwsinger** [comment]
Hi Nigel. I think this was the author's opinion; I am not sure whether I agree with you or them, but happily CSIRO is a member of the CG at the very least; and the idea and the substance of it were developed in the mailing lists (and notably with the editor, who's away on vacation, which is why Silvia volunteered to write it). I think we're as well covered as we can be; we're effectively responding to comment from the CSS WG and following their suggestions here, which is what wide review is supposed to achieve.

**Comment by nigelmegitt** [comment]
For IPR stuff CG membership is not relevant - it has to be WG membership or an explicit release. I don't think it being our resolution to a CSS WG comment or a construction based on their suggestions constitutes a release but happy to be educated if not! I suppose it depends on how detailed the wide review comment was, and if that commenter was also a member of TTWG.

**Comment by dwsinger** [comment]
I may be missing your concern here.

> On Jun 27, 2017, at 12:13 , Nigel Megitt <notifications@github.com> wrote:
> 
> For IPR stuff CG membership is not relevant

Sure it is. All members of the CG have signed a Contributor License Agreement, so if you’re worried about the Contributor, that’s covered. I have no way of getting IPR coverage from people who might have IPR, are not the Contributor, but who are not members of the WG (and nor does any WG).

> - it has to be WG membership or an explicit release. I don't think it being our resolution to a CSS WG comment or a construction based on their suggestions constitutes a release but happy to be educated if not! I suppose it depends on how detailed the wide review comment was, and if that commenter was also a member of TTWG.

The commenter was, IIRC, the CSS WG. The resolution was developed in dialog.


David Singer
Manager, Software Standards, Apple Inc.

**Comment by nigelmegitt** [comment]
>>  For IPR stuff CG membership is not relevant
>Sure it is. All members of the CG have signed a Contributor License Agreement, so if you’re worried about the Contributor, that’s covered.

Really? I don't think this does the same thing as the WG membership licensing obligation - unless there's been an explicit agreement made with all the CG members. The [IPR policy FAQ](https://www.w3.org/2003/12/22-pp-faq.html#which-groups) is clear that CG members have no licensing obligations. 

> The commenter was, IIRC, the CSS WG. The resolution was developed in dialog.

This falls squarely under the [Patent Policy FAQ on handling contributions from non-participants](https://www.w3.org/2003/12/22-pp-faq.html#non-participants) which says:

> When a contribution is being considered for actual inclusion in a document intended to become a Recommendation, the Chair should ask the Contributor to disclose any essential claims, and if there are any, the terms under which those claims would be licensed. Lack of a response to this request is a red flag.

If I understand ash-nazg correctly, it is designed to catch instances where this may be needed: marking the pull request as non-substantive is bypassing that. My concern is that we may end up in an indeterminate state with respect to licensing obligations.

**Comment by dwsinger** [comment]
> On Jun 27, 2017, at 12:35 , Nigel Megitt <notifications@github.com> wrote:
> 
> For IPR stuff CG membership is not relevant
> Sure it is. All members of the CG have signed a Contributor License Agreement, so if you’re worried about the Contributor, that’s covered.
> 
> Really? I don't think this does the same thing as the WG membership licensing obligation - unless there's been an explicit agreement made with all the CG members. The IPR policy FAQ is clear that CG members have no licensing obligations.

Ah. That section doesn’t mention CGs, it mentions only IGs, BGs and the like.  To join a CG, one must sign the Contributor License Agreement. Looks like that page was not updated when CGs were made.

See <https://www.w3.org/community/about/agreements/cla/>

> The commenter was, IIRC, the CSS WG. The resolution was developed in dialog.
> 
> This falls squarely under the Patent Policy FAQ on handling contributions from non-participants which says:
> 
> When a contribution is being considered for actual inclusion in a document intended to become a Recommendation, the Chair should ask the Contributor to disclose any essential claims, and if there are any, the terms under which those claims would be licensed. Lack of a response to this request is a red flag.

Yes. And I repeat, as a CG member, they made the licensing commitment on joining the CG.

> If I understand ash-nazg correctly, it is designed to catch instances where this may be needed: marking the pull request as non-substantive is bypassing that. My concern is that we may end up in an indeterminate state with respect to licensing obligations.

We’re always in an indeterminate state; we just try to wrestle it to being small.

We could mark it s substantive, and say that we’ve done what’s needed (we have an RF licensing commitment from both Silvia’s and Simon’s orgs).


David Singer
Manager, Software Standards, Apple Inc.

**Comment by nigelmegitt** [comment]
> To join a CG, one must sign the Contributor License Agreement. 

This is the Community CLA. I see that it includes:

> 9.2.1. Licensing Obligations to Resulting Specification. If I do not join the Corresponding Working Group, I agree to offer patent licenses according to the W3C Royalty-Free licensing requirements described in Section 5 of the W3C Patent Policy for my Contributions included in the resulting Recommendation. [snip]

which is probably the important bit here. 

> as a CG member, they made the licensing commitment on joining the CG.

Ah, again this is something that the FAQs haven't been updated to cover. In fact they give the impression that membership of one group doesn't cover any other group. In this case I think the CLA you referenced above probably does cover it for the TTWG too, so I consider myself partially re-educated!

> We could mark it s substantive, and say that we’ve done what’s needed (we have an RF licensing commitment from both Silvia’s and Simon’s orgs).

Simon is a member of the WG so is already covered, no problem. It would make sense to mark it as substantive and identify the RF licensing commitment from Silvia and any other CSSWG members who contributed to the solution design during the dialog. 

We could also make a feature request for ash-nazg to track CG members who have signed the CLA and relate the CG to the appropriate WG. In this case from the CLA text it seems that the commitment has already been made but ash-nazg doesn't know about it.

**Comment by dwsinger** [comment]
If you would like to mark it as substantive, and/or have me put this clarification in the Issue or PR, I am happy to do so (well, this conversation has done most of that)

> On Jun 27, 2017, at 12:59 , Nigel Megitt <notifications@github.com> wrote:
> 
> To join a CG, one must sign the Contributor License Agreement.
> 
> This is the Community CLA. I see that it includes:
> 
> 9.2.1. Licensing Obligations to Resulting Specification. If I do not join the Corresponding Working Group, I agree to offer patent licenses according to the W3C Royalty-Free licensing requirements described in Section 5 of the W3C Patent Policy for my Contributions included in the resulting Recommendation. [snip]
> 
> which is probably the important bit here.
> 
> as a CG member, they made the licensing commitment on joining the CG.
> 
> Ah, again this is something that the FAQs haven't been updated to cover. In fact they give the impression that membership of one group doesn't cover any other group. In this case I think the CLA you referenced above probably does cover it for the TTWG too, so I consider myself partially re-educated!
> 
> We could mark it s substantive, and say that we’ve done what’s needed (we have an RF licensing commitment from both Silvia’s and Simon’s orgs).
> 
> Simon is a member of the WG so is already covered, no problem. It would make sense to mark it as substantive and identify the RF licensing commitment from Silvia and any other CSSWG members who contributed to the solution design during the dialog.
> 
> We could also make a feature request for ash-nazg to track CG members who have signed the CLA and relate the CG to the appropriate WG. In this case from the CLA text it seems that the commitment has already been made but ash-nazg doesn't know about it.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by silviapfeiffer** [comment]
Relax. This is all a misunderstanding.
I tried to get ash-nazg to green my patch because I was under the impression that I was part of the CG and the WG as a member of both and accidentally got it to mark it as unsubstantial. I later found out that I had been removed as a CG member (not sure about WG, but I'd be happy to join that again also). I have re-joined the CG and all my contributions are covered, as they have been before. I can publicly confirm here that my contibutions fall under the licensing committment.
Hope this helps.

**Comment by nigelmegitt** [comment]
@silviapfeiffer thanks I thought it might be something like that. If you can join the WG that would be the easiest and cleanest solution from my perspective.

**Comment by silviapfeiffer** [comment]
Request sent.

**Comment by zcorpan** [comment]
Browser bugs for VTTRegion id:
https://bugs.chromium.org/p/chromium/issues/detail?id=755487
https://bugs.webkit.org/show_bug.cgi?id=168716
https://bugzilla.mozilla.org/show_bug.cgi?id=1049294
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11025636/

**Pull request merged**
