### PR TITLE
Prepare a WD

### PR DESCRIPTION
**Pull request by zcorpan**
I suggest we publish a WD 2015-12-10.

HTML output: https://rawgit.com/w3c/webvtt/wd-2015/archives/2015-12-10/Overview.html

Pubrules checker gives lots of errors though, will need to fix those...

### CODE REVIEW

**Comment by zcorpan** [comment]
OK I've fixed a bunch of errors, but some remain. I'm not sure how to fix them and I would like to not spend much more time on this. I would appreciate it if someone else could fix what remains and follow through to get it published, or tell me how exactly to fix something.

This was generated with https://github.com/tabatkins/bikeshed/pull/531 applied in bikeshed.

The date was just chosen arbitrarily, it can be changed to something else if necessary.

cc @dwsinger @plehegar

**Comment by plehegar** [comment]
@zcorpan I'll make sure we're good today. Thank you!

**Comment by plehegar** [comment]
Done
 http://www.w3.org/TR/2015/WD-webvtt1-20151208/

**Comment by nigelmegitt** [comment]
Just checking - we're not using the new stylesheet yet are we? This version clearly isn't using it right now.

**Comment by zcorpan** [comment]
Thank you @plehegar!

**Comment by plehegar** [comment]
@nigelmegitt correct. current target is February 1.

**Comment by nigelmegitt** [comment]
Thanks @plehegar

**Pull request merged**
