### PR TITLE
Rename "middle" to "center" throughout for consistency with CSS

### PR DESCRIPTION
**Pull request by zcorpan**
This affects align, position align, line align, and the DOM API.

Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=25956.

### CODE REVIEW

**Comment by zcorpan** [comment]
cc @eric-carlson @rickeyre @foolip

**Comment by foolip** [comment]
Since I filed the bug, it should come as not surprise that I support this. I've skimmed the diff and assume it's just search+replace, so :+1:

**Comment by zcorpan** [comment]
It's search+replace but I sanity-checked each instance in doing so.

I'd like a :+1: from @eric-carlson or @rickeyre (or other active implementor) before merging this.

**Comment by eric-carlson** [comment]
:+1: from me. Thanks Simon!

**Comment by zcorpan** [comment]
Great, thanks :-)

**Pull request merged**
