### PR TITLE
Add Silvia as editor

### PR DESCRIPTION
**Pull request by silviapfeiffer**
This is based on https://github.com/w3c/webvtt/pull/359 and can land after it. I'm adding myself as interim editor until we find a better person.

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
@dwsinger could you review this PR?

**Comment by dwsinger** [comment]
Think the affiliation is probably best shown as a W3C member (CSIRO), no? Some of the lines marked as changed I can't work out the implications here...(maybe they are not actually changed)...

**Comment by silviapfeiffer** [comment]
OK, I made the change to CSIRO. You only have to check the .bs file - the other one is automatically created by bikeshed and always updates to the latest references etc, so don't worry about those changes.

**Comment by silviapfeiffer** [comment]
@dwsinger I need a formal review on this PR to be able to land it :-)

**Comment by dwsinger** [comment]
reviewed and formally approved

**Comment by silviapfeiffer** [comment]
I'm landing this in the spirit of https://lists.w3.org/Archives/Public/public-texttracks/2017Sep/0035.html

**Pull request merged**
